### ISSUE TITLE
Windows: Populate path upon activation

### ISSUE THREAD

**Issue by hadim** [conda-forge/openjdk-feedstock#48]
Should we populate `%PATH%` during activation?

```
SET "PATH=%JDK_HOME%\jre\bin\server;%JDK_HOME%\bin\server;%JDK_HOME%\bin;%PATH%"
```

**Comment by ctrueden** [comment]
I just ran into this when trying to use [pyimagej](https://github.com/imagej/pyimagej) on Windows:

```
(pyimagej) PS>(base) PS>conda activate pyimagej
(pyimagej) PS>python -c 'import imagej; ij = imagej.init(); print(ij.getVersion())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\imagej\imagej.py", line 104, in init
    import imglyb
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\imglyb\__init__.py", line 38, in <module>
    config, _ = _init_jvm_options()
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\imglyb\__init__.py", line 33, in _init_jvm_options
    import scyjava
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\scyjava\__init__.py", line 122, in <module>
    jnius = _init_jvm()
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\scyjava\__init__.py", line 113, in _init_jvm
    import jnius
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\jnius\__init__.py", line 12, in <module>
    from .jnius import *  # noqa
ImportError: DLL load failed: The specified module could not be found.
```

Adding the openjdk package's `jre\bin\server` directory to the `PATH` fixes it:
```
$env:Path += ";$Env:CONDA_PREFIX\Library\jre\bin\server"
```

It would be nice if the environment activation script included the addition of `jre\bin\server` to the path. Nonetheless, for pyimagej, it still wouldn't enable use cases like dynamic installation from inside a Jupyter notebook, which never explicitly activates the Conda environment.

**Comment by mingwandroid** [comment]
> inside a Jupyter notebook, which never explicitly activates the Conda environment

Can you explain? It is up to the user to install Jupyter in their envs and activate them before running it.

**Comment by ctrueden** [comment]
@mingwandroid Sorry for being vague!

Sometimes it is useful for a Jupyter Python notebook to install additional Python packages into its current environment, from within the notebook itself. For Python packages available via Conda, one succinct way to achieve this is to include a first cell like the following:
```python
import sys
!conda install --yes --prefix {sys.prefix} -c conda-forge pyimagej openjdk=8
```

This is undoubtably a bit hacky, since it modifies the currently running Python environment. But it is useful when running Jupyter notebooks on [Binder](https://mybinder.org/), because it avoids needing to add the dependencies to that repository's `environment.yml`.

For example, the [SimpleITK-Notebooks repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) contains 25 example notebooks illustrating use of the [Insight Toolkit](https://itk.org), only [one of which](https://github.com/InsightSoftwareConsortium/itkwidgets/blob/v0.18.0/examples/ImageJImgLib2.ipynb) demonstrates integration with [ImageJ](https://imagej.net/) via [pyimagej](https://github.com/imagej/pyimagej). It would bloat the repository's dependencies to add `pyimagej` as a global dependency to `requirements.yml`, but if the notebook itself can install the package dynamically, this is very nice. This approach also lets each notebook have more fine-grained control over its environment.

While this sort of hack is outside the scope of Conda's primary intended use, it is still helpful that it works, and consequently, good to minimize our reliance on activation & deactivation scripts, so that these sorts of use cases remain viable.

**Comment by mingwandroid** [comment]
I think everyone agrees that the need for special purpose activation is to be avoided where-ever and whenever possible.

Thanks for the details. If conda were able to formalise the changes needed for activation (which @kalefranz and @scallesterain have done some work on) then it would be possible for the `conda` module to inject at least some of those environmental (mostly!) changes into the current python process (and remove them again on deactivation).

This *is* a bit race-conditioned, but IMHO it's better than recieving and investigating bug reports because people think this kind of thing should work in general because they've seen examples of it working on the internet via Google searches.
