### ISSUE TITLE
java.nio.file.Paths.get not working

### ISSUE THREAD

**Issue by hadim** [conda-forge/openjdk-feedstock#6]
I am having a bug running Java code with your package : 

```
java.lang.UnsatisfiedLinkError: /opt/local/conda/envs/scijava/jre/lib/amd64/libnio.so: libnet.so: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:573)
	at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:571)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.<clinit>(UnixNativeDispatcher.java:571)
	at sun.nio.fs.UnixFileSystem.<init>(UnixFileSystem.java:67)
	at sun.nio.fs.LinuxFileSystem.<init>(LinuxFileSystem.java:39)
	at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:46)
	at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:39)
	at sun.nio.fs.UnixFileSystemProvider.<init>(UnixFileSystemProvider.java:56)
	at sun.nio.fs.LinuxFileSystemProvider.<init>(LinuxFileSystemProvider.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:48)
	at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:63)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:96)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:90)
	at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.scijava.jupyter.commands.InstallScijavaKernel.installLanguage(InstallScijavaKernel.java:140)
	at org.scijava.jupyter.commands.InstallScijavaKernel.lambda$run$0(InstallScijavaKernel.java:79)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.scijava.jupyter.commands.InstallScijavaKernel.run(InstallScijavaKernel.java:77)
	at org.scijava.command.CommandModule.run(CommandModule.java:198)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Any idea ?

**Comment by hadim** [comment]
Ping @johanneskoester @sodre

**Comment by johanneskoester** [comment]
The libs are there, but it cannot find them because the zulu build puts them in a nonstandard location. It might be necessary that we set the LD_LIBRARY_PATH in the activate script? Maybe somebody from @conda-forge/core has an opinion what would be the canonical way to proceed?

**Comment by sodre** [comment]
Adding LD_LIBRARY_PATH is not the conda way. I'll try to patch the build. 

Patrick

**Comment by sodre** [comment]
@hadim,

I was not able to replicate your issue with conda-forge/openjdk. However, if I used continuum.io's openjdk then the problem comes up.

Can you make sure that you are using conda-forge's openjdk? Here is my output for `conda list`...
```
(openjdk) root at f8895893-26a7-68bb-8f4d-d10d39b9c4e0 in ~/openjdk-feedstock/recipe/test-nio on rpath*
# conda list
# packages in environment at /root/envs/openjdk:
#
openjdk                   8.0.112          zulu8.19.0.1_2    conda-forge
(openjdk) root at f8895893-26a7-68bb-8f4d-d10d39b9c4e0 in ~/openjdk-feedstock
```

**Comment by sodre** [comment]
@johanneskoester 
if @hadim is really using continuum's io openjdk, we should still add the test case for NIO. In that case we might as well take the time to upgrade Azul to the latest version. I can amend my PR #8 to do that.

Would you also be okay with me an additional maintainer?

**Comment by johanneskoester** [comment]
Of course, please add yourself! I am not using java and have almost no experience with it. I just needed it for the R migration. Hence, I would be very happy to have an additional maintainer.

**Comment by hadim** [comment]
Working now. Thanks for the help both of you.

**Comment by hadim** [comment]
FYI I think that the bug I saw was using the `openjdk` from the default channel and not the `conda-forge` one.
